### ISSUE TITLE
[9.0][BUG] Error "IllegalCharacterError: EAN code can only contain numbers." when generating a new barcode

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-barcode#102]
- Go to runbot: https://runbot.odoo-community.org/runbot/150/9.0 (in my case: http://3291991-9-0-25cf9c.runbot2.odoo-community.org/web?debug=1#id=157&view_type=form&model=product.template&menu_id=102&action=112)
- Try to generate a barcode of any new product
- Check "Default nomenclature" in Settings -> Sequence -> Barcode nomenclature (in my case. http://3291991-9-0-25cf9c.runbot2.odoo-community.org/web?&debug=#id=1&view_type=form&model=barcode.nomenclature&menu_id=235&action=73)
- You get error:

```


Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-9.0/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-9.0/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/stock-logistics-barcode/barcodes_generator_product/models/product_template.py", line 36, in generate_barcode
    self.product_variant_ids.generate_barcode()
  File "/.repo_requirements/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/build/OCA/stock-logistics-barcode/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 57, in generate_barcode
    item.barcode = barcode_class(custom_code)
  File "/.repo_requirements/virtualenv/python2.7/local/lib/python2.7/site-packages/barcode/ean.py", line 42, in __init__
    raise IllegalCharacterError('EAN code can only contain numbers.')
IllegalCharacterError: EAN code can only contain numbers.
```
@legalsylvain  do you have any idea please?

**Comment by legalsylvain** [comment]
Your setting was : 
![image](https://user-images.githubusercontent.com/3407482/28968015-46444fbe-791e-11e7-8e5b-2f800d8724b3.png)


The correct one is : 
![image](https://user-images.githubusercontent.com/3407482/28968004-395b71a6-791e-11e7-8388-4da4d510166f.png)

".*" pattern is not managed by the module.
regards.

**Comment by legalsylvain** [comment]
(In my previous comment, there are 13 "." In reality, we need 12 ".". (the 13st char is control char).

**Comment by rafaelbn** [comment]
Thanks! 😄
