### ISSUE TITLE
[BUG] stock_scanner: unable to install stock_scanner in demo mode

### ISSUE THREAD

**Issue by astirpe** [OCA/stock-logistics-barcode#158]
Reproducible in V11. Not checked whether it occurs in other versions.

Steps to reproduce:

- Create a fresh database in Demo mode (Load demonstration data = True)
- Rename the company name "YourCompany" to something else, for example: "HappyCompany"
- install stock_scanner

Actual behavior:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/modules/loading.py", line 184, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/stock_scanner/load_scenario.py", line 223, in scenario_convert_file
    import_scenario(env, module, fp, mode, directory, filename)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/stock_scanner/load_scenario.py", line 111, in import_scenario
    'Company not found: %s' % scenario_values['company_id'])
ValueError: Company not found: False
```

**Comment by rousseldenis** [comment]
@astirpe There is a fix for that now.
