### ISSUE TITLE
tr_barcode_on_picking, error in create picking v7

### ISSUE THREAD

**Issue by dhecar** [OCA/stock-logistics-barcode#16]
I'm getting this error on picking creation. The module is recently download from github. Thanks in advance

Client Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1137, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/odoo/odoo-server/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/odoo/odoo-server/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 193, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 133, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 202, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 190, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/odoo/custom/addons/magento/sale-wkfl/sale_exceptions/sale.py", line 159, in action_button_confirm
    cr, uid, ids, context=context)
  File "/opt/odoo/odoo-server/addons/sale/sale.py", line 581, in action_button_confirm
    wf_service.trg_validate(uid, 'sale.order', ids[0], 'order_confirm', cr)
  File "/opt/odoo/odoo-server/openerp/workflow/wkf_service.py", line 119, in trg_validate
    res2 = instance.validate(cr, id, ident, signal)
  File "/opt/odoo/odoo-server/openerp/workflow/instance.py", line 43, in validate
    workitem.process(cr, witem, ident, signal, force_running, stack=stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 60, in process
    ok = _split_test(cr, workitem, activity['split_mode'], ident, signal, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 175, in _split_test
    _join_test(cr, t[0], t[1], ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 183, in _join_test
    create(cr,[activity], inst_id, ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 40, in create
    process(cr, res, ident, stack=stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 60, in process
    ok = _split_test(cr, workitem, activity['split_mode'], ident, signal, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 175, in _split_test
    _join_test(cr, t[0], t[1], ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 183, in _join_test
    create(cr,[activity], inst_id, ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 40, in create
    process(cr, res, ident, stack=stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 60, in process
    ok = _split_test(cr, workitem, activity['split_mode'], ident, signal, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 175, in _split_test
    _join_test(cr, t[0], t[1], ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 183, in _join_test
    create(cr,[activity], inst_id, ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 40, in create
    process(cr, res, ident, stack=stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 52, in process
    result = _execute(cr, workitem, activity, ident, stack)
  File "/opt/odoo/odoo-server/openerp/workflow/workitem.py", line 106, in _execute
    returned_action = wkf_expr.execute(cr, ident, workitem, activity)
  File "/opt/odoo/odoo-server/openerp/workflow/wkf_expr.py", line 67, in execute
    return _eval_expr(cr, ident, workitem, activity['action'])
  File "/opt/odoo/odoo-server/openerp/workflow/wkf_expr.py", line 57, in _eval_expr
    ret = eval(line, env, nocopy=True)
  File "/opt/odoo/odoo-server/openerp/tools/safe_eval.py", line 288, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odoo-server/openerp/osv/orm.py", line 378, in function_proxy
    return attr(self._cr, self._uid, [self._id], _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/sale_stock/sale_stock.py", line 455, in action_ship_create
    self._create_pickings_and_procurements(cr, uid, order, order.order_line, None, context=context)
  File "/opt/odoo/odoo-server/addons/sale_stock/sale_stock.py", line 423, in _create_pickings_and_procurements
    picking_id = picking_obj.create(cr, uid, self._prepare_order_picking(cr, uid, order, context=context))
  File "/opt/odoo/custom/addons/extras/stock-logistics-barcode/tr_barcode_config/barcode/barcode_osv.py", line 123, in create
    self._name, context=context)
  File "/opt/odoo/custom/addons/extras/stock-logistics-barcode/tr_barcode_config/barcode/barcode_osv.py", line 67, in create_barcode
    if not context.get('__copy_data_seen'):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by lasley** [comment]
Hi @dhecar - Sorry but I'm pretty sure these modules won't be touched again. I went ahead and filed a PR to deprecate them in #81
