### ISSUE TITLE
[v10,v11][stock_scanner] The sentinel session session not started

### ISSUE THREAD

**Issue by bunhin** [OCA/stock-logistics-barcode#211]
Hi all,
I have read line by line the configuration and how to use guide but can not get the point to start the sentinel session with the scanner device

already install odoo-sentinel  with  pip3 install odoo-sentinel, and success (inside the same odoo virtual environment)

I have successfully installed stock_scanner module on Odoo V11 fresh install, with demo data loaded. sentinel technical user is there, and have enabled login in setting-->warehouse-->setting

I have one SMART SCANNER DEVICE (android os), and have installed SSH client
Scanner device and odoo-server in the same local network (wifi)
I have login to odoo-server using ssh-client (juice ssh client), success
But nothing happen to the smart barcode screen

Tried to create .odoo-sentinelrpc file  and placed inside user directory
Have tried to use sentinel user in scanner hardware record file (default was empty, the sentinel user put in there)

But still, no any sentinel session seem to start

Please help, what step is missed or wrong here. Thank you.

**Comment by bunhin** [comment]
after sometime the module installed, i found this error on log, and the have issue on css rendering such as database manager page get messy, icon of app logo are not shown

2019-09-18 06:17:08,777 1104 ERROR dbnameXX odoo.addons.base.ir.ir_cron: Call from cron Remove the current user_id and scenario values on session timeout for server action #588 failed in Job #9
Traceback (most recent call last):
  File "/opt/odoo11/odoo/addons/base/ir/ir_cron.py", line 102, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo11/odoo/addons/base/ir/ir_actions.py", line 552, in run
    eval_context = self._get_eval_context(action)
  File "/opt/odoo11/addons/mail/models/ir_actions.py", line 65, in _get_eval_context
    eval_context = super(ServerActions, self)._get_eval_context(action=action)
  File "/opt/odoo11/odoo/addons/base/ir/ir_actions.py", line 508, in _get_eval_context
    model = self.env[model_name]
  File "/opt/odoo11/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo11/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'scanner.hardware'
2019-09-18 06:18:09,872 1104 ERROR xxxxdbnamexx odoo.addons.base.ir.ir_cron: Call from cron Remove the current user_id and scenario values on session timeout for server action #588 failed in Job #9
Traceback (most recent call last):
  File "/opt/odoo11/odoo/addons/base/ir/ir_cron.py", line 102, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo11/odoo/addons/base/ir/ir_actions.py", line 552, in run
    eval_context = self._get_eval_context(action)
  File "/opt/odoo11/addons/mail/models/ir_actions.py", line 65, in _get_eval_context
    eval_context = super(ServerActions, self)._get_eval_context(action=action)
  File "/opt/odoo11/odoo/addons/base/ir/ir_actions.py", line 508, in _get_eval_context
    model = self.env[model_name]
  File "/opt/odoo11/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo11/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'scanner.hardware'
 
what is causing this error
