### ISSUE TITLE
object has no attribute 'get_barcode_class'

### ISSUE THREAD

**Issue by MounirKammoun** [OCA/stock-logistics-barcode#273]
I have installed the module "Generate Barcodes for Products". When I create a new product, I get the following error :
Erreur:
```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 747, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 727, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-304>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-179>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/usr/addons/barcodes_generator_product/models/product_template.py", line 45, in create
    template = super(ProductTemplate, self).create(vals)
  File "<decorator-gen-160>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/product/models/product_template.py", line 350, in create
    templates.with_context(create_from_tmpl=True).create_variant_ids()
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/product/models/product_template.py", line 547, in create_variant_ids
    Product.create(variants_to_create)
  File "<decorator-gen-188>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/addons/product_sequence/models/product_product.py", line 39, in create
    return super(ProductProduct, self).create(vals)
  File "<decorator-gen-171>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/product/models/product.py", line 342, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-111>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-139>", line 2, in create
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo-12.0.20190918-0/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 47, in create
    record.generate_barcode()
  File "/usr/addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 70, in generate_barcode
    barcode_class = barcode.get_barcode_class(
AttributeError: 'NoneType' object has no attribute 'get_barcode_class'
```
I installed  'python-barcode' with `pip3 install python-barcode` but getting the same error.

**Comment by legalsylvain** [comment]
Hi @MounirKammoun : For which version ?

**Comment by MounirKammoun** [comment]
Hi @legalsylvain 
Odoo 12.

**Comment by legalsylvain** [comment]
I think that you have not the good version of the package.
Step to reproduce : 
```
# create a fresh virtualenv
virtualenv env --python=python3
# install the library
./env/bin/pip install python-barcode
```
Result : 
```
Collecting python-barcode
  Using cached python_barcode-0.11.0-py3-none-any.whl (214 kB)
Installing collected packages: python-barcode
Successfully installed python-barcode-0.11.0
```
Run the virtualenv ``./env/bin/python``
Inside, 
```
import barcode
barcode.get_barcode_class("ean13")
```
Result : 
```
<class 'barcode.ean.EuropeanArticleNumber13'> 
```
Hope it will help

Kind regards.

**Comment by MounirKammoun** [comment]
It works!
Thank you very much!
Best regards
