### ISSUE TITLE
OperationalError: Unable to use a closed cursor.

### ISSUE THREAD

**Issue by NillerVillar** [OCA/stock-logistics-barcode#93]
Hello, I´m in Odoo v10.0 CE, i want to autogenerate the barcode EAN-13 in the new products.
I Install **barcodes_generator_abstract** and **barcodes_generator_product**.
I generate a barcode nomenclature and barcode pattern 23...........
The first generation of barcode works well, but if i want to create a new products, this is the error:
If i update the addon barcodes_generator_product works well one more time but in the second time fail again.

```
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 874, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/barcodes_generator_product/models/product_template.py", line 45, in create
    template = super(ProductTemplate, self).create(vals)
  File "/odoo/odoo-server/addons/product/models/product_template.py", line 267, in create
    template.create_variant_ids()
  File "/odoo/odoo-server/addons/product/models/product_template.py", line 400, in create_variant_ids
    'attribute_value_ids': [(6, 0, variant_ids.ids)]
  File "/odoo/odoo-server/addons/product/models/product.py", line 315, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/custom/addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 40, in create
    if barcode_rule.exists():
  File "/odoo/odoo-server/odoo/models.py", line 4406, in exists
    self._cr.execute(query, [tuple(ids)])
  File "/odoo/odoo-server/odoo/sql_db.py", line 140, in wrapper
    **raise psycopg2.OperationalError(msg)
OperationalError: Unable to use a closed cursor.**
```

The explication of the error:
**exception psycopg2.OperationalError**
Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc. It is a subclass of DatabaseError.

**Comment by dvdhinesh** [comment]
I also faced this error on the OCA runbot `https://runbot.odoo-community.org/runbot/150/10.0`
The same happens in local also.

**Comment by yasserkaddour** [comment]
I had the same the same error, tell me if there is anything I can do to help you debug the issue.

**Comment by legalsylvain** [comment]
Hi, I can not reproduce the bug.
- Local environement : All is OK. (Ubuntu Env + OCB 10.0, based on odoo 10.0 CE)
- On runbot, after relaunching build, all is OK.

Could you provides 
- your environment ?
- the branch you are using ? 
- the exact nomenclature setting and sequence setting (if any).

By the way, your pattern is bad. 23........... is 13 digit, and the pattern should be 12 digit, excluding control digit. (See Odoo exemple).

regards.

**Comment by dvdhinesh** [comment]
@legalsylvain I just tested again in OCA runbot and that `closed cursor` error is still there.... 
Take a look at this [video](https://youtu.be/gjDgKeKAIu0)...
I just changed the existing rule from manual to sequence...

**Comment by Nucleardragon88** [comment]
I have same problem：

2017-08-21 05:40:04,432 1881 ERROR erp.gigatelco.com odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/barcodes_generator_product/models/product_template.py", line 45, in create
    template = super(ProductTemplate, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product/models/product_template.py", line 269, in create
    template.with_context(create_from_tmpl=True).create_variant_ids()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product/models/product_template.py", line 402, in create_variant_ids
    'attribute_value_ids': [(6, 0, variant_ids.ids)]
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product/models/product.py", line 316, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 40, in create
    if barcode_rule.exists():
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4414, in exists
    self._cr.execute(query, [tuple(ids)])
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 153, in wrapper
    raise psycopg2.OperationalError(msg)
OperationalError: Unable to use a closed cursor.

**Comment by Nucleardragon88** [comment]
I can create only 2 new products with automatic generation of barcode then I get an error, see previous message.

Then if I restart odoo (service odoo restart) I can create 2 products again, when I try to create a third product, I get an error again then service odoo restart again help and so again and again

**Comment by Nucleardragon88** [comment]
This error happens only if you select checkbox "Automatic Generation" when Generate Type is "Base managed by Sequence"

**Comment by diranetafen** [comment]
I have the same issue ! @Nucleardragon88  your observation is right , his error happens only if you select checkbox "Automatic Generation" 
Thanks in advance for somebady who resolce this issue to share the solution
I'm currently use workaround : uncheck "Automatic Generation"

**Comment by evgk** [comment]
Hey,
  I quickly looked into it, looks like the culprit is this line:
@tools.ormcache('model')
in

    @api.model
    @tools.ormcache('model')
    def get_automatic_rule(self, model):
        """ It provides a cached indicator for barcode automation.

        Note that this cache needs to be explicitly cleared when
        `generate_automate` is changed on an associated `barcode.rule`.

        Args:
            model (str): Name of model to search for.
        Returns:
            BarcodeRule: Recordset of automated barcode rules for model.
        """
        return self.search([
            ('generate_model', '=', model),
            ('generate_automate', '=', True),
        ])

Looks like this line leads to the model being returned with a closed cursor from the cache. If you call this function the first time, it works since the result is not cached, but the subsequent calls lead to this cursor-issue. Commenting out the line fixes the problem.

**Comment by lasley** [comment]
Thanks for the breakdown everyone (especially @evgk). I think I have a solid fix that will still leverage cache but not exhibit this issue. Can you test #103 please?
